### ISSUE TITLE
Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by ColinMaudry** [entrecode/json-schema-remote#1]
I try to validate local data with a remote schema. I'm really happy I finally found a tool that handles remote schema :)

However, in command line, I get the following error:

```bash
$ json-schema-remote test-output.json https://raw.githubusercontent.com/etalab/format-commande-publique/master/sch%C3%A9mas/json/paquet.json
downloading from  test-output.json 

downloading from  https://raw.githubusercontent.com/etalab/format-commande-publique/master/sch%C3%A9mas/json/paquet.json 

Cannot read property 'statusCode' of undefined

```

**Comment by ColinMaudry** [comment]
I don't get this error when the data is also remote. Are both data and schema expected to be remote?

**Comment by simon-scherzinger** [comment]
Sorry for getting back to this so late.

The problem is that json-schema-remote only supports two types of input. A JSON object OR a URL string.

The usage with a local file path is not supported.
